### PR TITLE
Update testing section, add use cases, update formatting, remove all mentions of GAME_NAME

### LINKED ISSUE #239: Inconsistency in friend --list in DG
Screenshot 2021-11-07 at 4 19 58 AM

Draco should be `Draco`

### LINKED ISSUE #252: Confusing explanation in DG
A bit confusing as to which list the JavaFX-based `UI` is observing. There has been no mention of the term `ObservableList`, which is the main reason the `UI` is being updated whenever there's a change to the underlying `SortedList<Friend>`, which is built on top of the `FilteredList<Friend>`, which in turn is built on top of a `FriendsList`.

image

### LINKED ISSUE #253: Inconsistent heading convention in DG
Some headings are followed by a `:`, while some aren't. Perhaps convert all headings to not use `:`.

image

### LINKED ISSUE #257: Fix colons and consistency issues in DG header
image

### PR DESCRIPTION
**Pull request by tau-bar**
# Changes:
* Update testing section - fix bugs and put all entities in '$ENTITY' format
* Update all mentions of GAME_NAME to GAME_ID
* Added use cases for recommend, schedule, skill and unlink
* Update delete feature implementation section and added one sequence diagram

# Issues:
* Resolves #253 
* Resolves #252 
* Resolves #239 
* Resolves #257

### CODE REVIEW

**Comment by LZher385** [comment]
image
I believe the underlined should be `parse(" --delete Dota")` instead(there's a space in front of the two dashes)

**Comment by tau-bar** [comment]
> image I believe the underlined should be `parse(" --delete Dota")` instead(there's a space in front of the two dashes)

Good catch, thanks

**Comment by kevin9foong** [comment]
Some minor recommendations for changes: 
1. The ref box should be in front the of lifeline bars 
eg. 
image
instead of 
image

2. The diagram image does not seem to reflect the new changes to the `.puml` files. 
Maybe you can re-export the image? 
image
Still command being shown 

(Side note: why not use a more descriptive name instead of just 'c'? May have to update Marcus's part as well) 

3. For the ref frame, lets follow the CS2103T example and put the sd box outside (have to update Marcus's one also) 
image
notice how the mainframe 'sd ...' wraps the entire sequence diagram 
instead of this 
image

**Review by kevin9foong — CHANGES_REQUESTED** [review]
Some minor recommendations for changes: 
1. The ref box should be in front the of lifeline bars 
eg. 
image
instead of 
image

2. The diagram image does not seem to reflect the new changes to the `.puml` files. 
Maybe you can re-export the image? 
image
Still command being shown 

(Side note: why not use a more descriptive name instead of just 'c'? May have to **update Marcus's part** as well) 

3. For the ref frame, lets follow the CS2103T example and put the sd box outside (have to **update Marcus's one also**) 
image
notice how the mainframe 'sd ...' wraps the entire sequence diagram 
instead of this 
image

You can see the recommend sequence diagram for reference: 
image

4. For the UG, we need to update the image descriptions to match and possibly remove redundant word 'Screenshot:' 
 
image
this can be made more informative with eg. help command popup window after 'help' command is executed. 

image
Consistency with image descriptions eg. Command box after... gitGud after...

**Comment by kevin9foong** [comment]
Another DG bug in terms of ref found, use the 'ref over' syntax instead. 
image

There should not be [ ] in the ref notation

**Review by kevin9foong — APPROVED** [review]
Nice work fixing the bugs, LGTM

**Pull request merged**
